### ISSUE TITLE
Detected problems with app native libraries

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/template-master-detail-kinvey-ng#44]
_From @vitaliy-kuzmich on October 28, 2017 11:18_

Hello, strange popup message:

### Tell us about the problem
Detected problems with app native libraries
(please consult log for details)
libavcodec.so: text relocations
etc...

### Which platform(s) does your issue occur on?
Android-X86_64 7.1.2 VM VirtualBox
Android-X86_64 6.0 VM Qemu
Gnu/linux x86_64 host machine
![2017_10_28_14 11 1509189103s_screen](https://user-images.githubusercontent.com/9258443/32133942-c05dda04-bbea-11e7-9f69-f4999c2101d3.png)

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
3.2.1
tns-template-master-detail-kinvey-ng without any changes

there are no any errors in logs.

_Copied from original issue: NativeScript/NativeScript#4999_

**Comment by NickIliev** [comment]
@vitaliy-kuzmich this issue seems to be related to native Android Nougat issue hit with [multiple native projects](https://www.google.bg/search?rlz=1C1CHBF_enBG741BG742&ei=NOn2Wei2OdKN0gX47rjADA&q=Detected+problems+with+app+native+libraries+libavcodec.so%3A+text+relocations&oq=Detected+problems+with+app+native+libraries+libavcodec.so%3A+text+relocations&gs_l=psy-ab.3...11766.11975.0.12645.2.2.0.0.0.0.149.255.0j2.2.0....0...1.1.64.psy-ab..0.1.106...35i39k1j0i203k1.0.NPwnrI2azxg). However I was testing on my side on several Nougat devices and emulators but was not able to reproduce the issue.

I have noticed taht you are using Android emulator in VirtualBox - can you try to verify you have the satisfied the [system requirement](https://docs.nativescript.org/start/ns-setup-linux#system-requirements)s and [create an AVD](https://docs.nativescript.org/tooling/android-virtual-devices)

**Comment by vitaliy-kuzmich** [comment]
yeah, I do not use android studio because it is broken(has a lot of problems in order to use it). I did as (https://docs.nativescript.org/tooling/android-virtual-devices) but  
" /opt/android-sdk/tools/emulator -avd dro25 -netspeed full -netdelay none
[139937208608576]:ERROR:android/android-emu/android/qt/qt_setup.cpp:28:Qt library not found at /opt/android-sdk/emulator/lib64/qt/lib
Could not launch '/opt/android-sdk/emulator/qemu/linux-x86_64/qemu-system-x86_64': No such file or directory
". It is not possible to launch AVD from android-studio due to mentioned problem.

For some reasons android studio thinks that qemu bin should be in the android folder. Anyway I tried it with qemu and experiencing the same issue(Android-X86_64 6.0 VM Qemu). Let me try to run it with android image from google play ...

**Comment by vitaliy-kuzmich** [comment]
need help, actually AVD downloaded image to the "/opt/android-sdk/system-images/android-25/google_apis/x86_64/userdata.img", I see there is custom kernel-qemu, I'd like to get the run script of qemu, @NickIliev  do you know where I can get that ? 
it should looks like this : 
```
qemu-system-x86_64 -boot d \
-vga std \
-drive file=/dev/sda10,index=0,cache=writeback \
-smp 2,cores=2,threads=1 -cpu host,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time -m 2G \
-enable-kvm -machine type=pc,accel=kvm -net nic -net bridge,br=br0 -soundhw ac97 \
```

**Comment by vitaliy-kuzmich** [comment]
upd: tried tns --sdk 17, message gone..

**Comment by andresg747** [comment]
Hi, sorry to open this issue again but I'm having the exact same popup message every time I try to run on my device. Not having the issue on emulator though.

**Which platform(s) does your issue occur on?**
I'm using tns version 3.3.0
Host Machine: Win10 x64
Emulator:  Pixel_API_23_-_Marshmellow
Device: Asus Zenfone 2 - Lineage OS (Nougat 7.1.2)
Tried debugging with --sdk 17 flag. Error appears on device, not in emulator.

Any advice?

**Comment by droidMakk** [comment]
I'm also getting an error, just now started to learn. I have a **Zenfone 5** device and hostmachine is  **Windows 10 x64**

**Comment by behelit** [comment]
Nougat / Oreo will complain about text relocations, irrespective of target SDK.
This can usually be fixed by compiling with the latest ndk.
