### ISSUE TITLE
Error running from template

### ISSUE THREAD

**Issue by ashrafaa** [NativeScript/template-master-detail-kinvey-ng#53]
Just tried creating new app from the template and it hits me with following error
`tns create basic --template https://github.com/NativeScript/template-master-detail-kinvey-ng`
`added 213 packages in 16.258s
cp: no such file or directory: /../basic/node_modules/https:/github.com/NativeScript/template-master-detail-kinvey-ng/*`

Afterwards I tried to clone the repo instead and run `npm i`, and got following instead 
`postinstall script running...
{ Error: Cannot find module '/../package.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at getAppRootFolder.then (/../template-master-detail-kinvey-ng/tools/postinstall.js:30:33) code: 'MODULE_NOT_FOUND' }`

**Comment by manoldonev** [comment]
You should not be cloning the repo -- `tns create` command is the way to go.

Can you try the following command as well (it will create an app from the published version of this template):
`tns create basic2 --template tns-template-master-detail-kinvey-ng`

Are you able to create apps from any other NativeScript Angular templates?
`tns create basic3 --template tns-template-master-detail-ng`
`tns create basic4 --ng`

Are you using the latest version of NativeScript CLI 3.3.1? Also what are your node, npm, and OS versions?

**Comment by ashrafaa** [comment]
Yes it's working now, thanks! Guess I should not be using the full path with github link?

**Comment by manoldonev** [comment]
Generally `tns-template-master-detail-kinvey-ng` points to the current official version published to npm: https://www.npmjs.com/package/tns-template-master-detail-kinvey-ng, while the full path https://github.com/NativeScript/template-master-detail-kinvey-ng points to the master branch of the repo here.

It is possible that the master branch of the repo might be ahead of the npm package, however, I cannot reproduce the problem you are experiencing with either one of them.
