### ISSUE TITLE
Project Not running throwing error

### ISSUE THREAD

**Issue by dlucidone** [NativeScript/template-master-detail-kinvey-ng#69]
Creating file: /Users/ravi/Documents/Extra/template-master-detail-kinvey-ng-master/webpack.config.js
Creating file: /Users/ravi/Documents/Extra/template-master-detail-kinvey-ng-master/app/vendor-platform.android.ts
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/ravi/Documents/Extra/template-master-detail-kinvey-ng-master/app/vendor-platform.android.ts'

**Comment by manoldonev** [comment]
Does shorter name for the template install directory make any difference (e.g. master-detail-kinvey-ng)?

**Comment by manoldonev** [comment]
@dlucidone Also, as noted in the [readme](https://github.com/NativeScript/template-master-detail-kinvey-ng/edit/master/README.md) you should create app from the template either via: `tns create my-app-name --template tns-template-master-detail-kinvey-ng` (uses npm published version of the template) or `tns create my-app-name --template tns-template-master-detail-kinvey-ng` (uses master branch of the template). You should not clone the repo and run `npm install` on it -- it will not work.
